name: "CI"

permissions: "read-all"

on:
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: "bash"

env:
  FORCE_COLOR: "1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12-dev"]

    name: "Test (${{ matrix.python-version }})"
    runs-on: "ubuntu-latest"
    continue-on-error: false

    steps:
    - name: "Checkout repository"
      uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"

    - name: "Setup Python"
      uses: "actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9"
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Run tests"
      run: |
        python -m pip install -r requirements/test.txt
        python -m pip install .
        pytest tests/
